easy_admin:
   site_name: '<h1>Administration | La Réunion</h1>'
   entities:
       # List the entity class name you want to manage
      Users:
         class: App\Entity\Users
         form:
                fields:
                    - { property: 'email', type: 'email', label: 'email' }
                    - { property: 'password', type: 'password', label: 'password' }
      Articles:
         class: App\Entity\Articles

      Categories:
         class: App\Entity\Categories
         form:
                fields:
                    - { property: 'nom', type: 'text', label: 'Name' }
                    - { property: 'slug', type: 'text', label: 'Slug' }

      Commentaires:
         class: App\Entity\Commentaires

      MotsCles:
         class: App\Entity\MotsCles
         form:
                fields:
                    - { property: 'mot_cle', type: 'text', label: 'Mots Clé' }
                    - { property: 'slug', type: 'text', label: 'Slug' }
      Products:
         class: App\Entity\Products
         form:
                fields:
                    - { property: 'productsCategories', label: 'Catégorie' }
                    - { property: 'title', type: 'text', label: 'Title' }
                    - { property: 'content', type: 'text', label: 'Content' }
                    - { property: 'phone', type: 'text', label: 'Phone' }
                    - { property: 'email', type: 'text', label: 'email' }
                    - { property: 'website', type: 'text', label: 'Site Web' }
                    - { property: 'bookingurl', type: 'text', label: 'Booking URL' }
                    - { property: 'imageFile', type: 'file', label: 'Image' }
                    - { property: 'img', type: 'text', label: 'Nom Image' }
                    - { property: 'usercreate', label: 'Utilisateur' }
                    - { property: 'datecreate', type_options: { widget: 'single_text' }}
                    - { property: 'publish', label: 'Published Status' }
      
      ProductCategory:
         class: App\Entity\ProductsCategory

   user:
      name_property_path: 'fullName'
      display_name: true
      display_avatar: false
   design:
      brand_color: '#fe5f5f'
      menu:
         - { entity: 'Users', icon: 'user' }
         - { label: 'Listings' }
         - { entity: 'Products', label: 'Produits', icon: 'tag' }
         - { entity: 'ProductCategory', label: 'Catégories', icon: 'tag' }
         - { label: 'Blog' }
         - { entity: 'Articles', label: 'Articles', icon: 'tag' }
         - { entity: 'Categories', label: 'Catégories', icon: 'tag' }
         - { entity: 'MotsCles', label: 'Mots Clés', icon: 'tag' }
         - { entity: 'Commentaires', label: 'Commentaires', icon: 'tag' }