easy_admin:
   site_name: '<h1>Administration | La Réunion</h1>'
   entities:
       # List the entity class name you want to manage
       - App\Entity\Users
       - App\Entity\Articles
       - App\Entity\Categories
       - App\Entity\Commentaires
       - App\Entity\MotsCles

   user:
      name_property_path: 'fullName'
      display_name: true
      display_avatar: false
   design:
      brand_color: '#fe5f5f'
      menu:
         - { entity: 'Users', icon: 'user' }
         - { label: 'Blog' }
         - { entity: 'Articles', label: 'Articles', icon: 'tag' }
         - { entity: 'Categories', label: 'Catégories', icon: 'tag' }
         - { entity: 'MotsCles', label: 'Mots Clés', icon: 'tag' }
         - { entity: 'Commentaires', label: 'Commentaires', icon: 'tag' }